project:
  type: website
  output-dir: docs

website:
  title: "Carlotta Angiolillo"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: print.qmd
        text: Print Reporting
      - href: audio.qmd
        text: Audio Reporting
      - href: photos.qmd
        text: Photojournalism

format:
  html:
    theme: brite
    css: styles.css
    toc: true

editor: visual