---
title: "Data Journalism"
---

Inspired by the work of investigative journalists, I completed a data science minor while at Northwestern to give myself the skills necessary to uncover stories I wouldn't be able to find otherwise.

I took seven courses for the minor and learned skills in statistics, data visualization, data science techniques, data journalism, data cleaning and predictive modeling.

These are some projects I've completed for both data science and data journalism courses while I was a student at NU.

[Data science class project - download to view!](https://drive.google.com/file/d/1HA6NjUWc1GPIKK3U4Dsvo6ZG-NEXWP6x/view)

[Data journalism class project - Cook County diversions program data](https://carlottaang76.quarto.pub/diversions-data-story/)

[The Daily Northwestern - campus-wide polling data](https://dailynorthwestern.com/2025/05/07/campus/poll-fall-and-now/)

[Investigative journalism class project - naturalization ceremonies in Chicago amid ICE presence](https://drive.google.com/drive/folders/16H1W9EoOOI6r-mdjqYNuUK_cv1jMHblf?usp=drive_link)

I was also co-president of [Northwestern's Data Journalism Collective](https://www.instagram.com/djc.nu/) from June 2025 through May 2026. In this role, I created a community for student journalists to learn more about data journalism and connect with others who share the same passion. One of my favorite events I put together was a guest speaker event on FOIA requests with Adam Rhodes of IRE. 