---
title: "Resume"
---

**EDUCATION**

**Northwestern University** \| B.S. in **Journalism** \| Minor in **Data Science** \| September **2023** - Expected June **2026**

**INTERNSHIPS AND FREELANCE WORK**

*The Columbia Missourian, Incoming Reporting Intern (Starting June 2026 through August 2026)*

-   GA reporter via Scripps Howard Fund internship program; responsible for pitching, reporting and writing daily stories for Columbia, MO community

*Chicago Public Media / WBEZ Chicago, Freelancer (September 2025 - December 2025)*

-   Co-produced audio segment for April 12 *Prisoncast!* show with incarcerated students and WBEZ reporters

*Houston Chronicle, Opinion Team Intern (June 2025 - August 2025)*

-   Edited and fact checked contributed op-eds; solicited op-eds from diverse voices in the Houston area

-   Pitched, reported and wrote columns; published stories on WCM; promoted stories on X and Reddit

*Covering Katy News, Freelance Reporter (June 2024 - September 2024)*

-   Pitched and wrote 10+ hyperlocal stories; established source relationships with community members

**NORTHWESTERN OPPORTUNITIES**

*The Daily Northwestern, Reporter (October 2023 - Present)*

-   Cover campus and Evanston stories, photograph local events and sports games, analyze campus poll data

*Medill News Service, Congressional Reporter - Health & Science (January 2026 - March 2026)*

-   Covered health and science policy developments in D.C.; produced accurate reporting on tight deadlines

*The Daily Northwestern, Features Editor (August 2025 - December 2025)*

-   Edited, published one to three longform feature stories weekly, uploaded with FLEX Pro WordPress (SNO)

-   Managed publishing schedule, budget of story pitches and weekly check-ins with team of 25+ reporters

*Data Journalism Collective, Co-President (June 2025 - May 2026)*

-   Organized club meetings, workshops and speakers to increase student engagement with data journalism

*The Daily Northwestern, Audience Engagement Editor (March 2025 - June 2025)*

-   Collaborated with desk editors, social media team to increase engagement across digital platforms

-   Hosted community listening session to improve news coverage, communicated feedback to newsroom

*The Daily Northwestern, Digital Managing Editor (August 2024 - December 2024)*

-   Edited all content from seven digital-focused desks, including data visualization, audio, photo, newsletter

*The Daily Northwestern, Audio Editor (March 2024 - June 2024)*

-   Published one to three podcasts weekly, uploaded using SoundCloud, Spotify, Cyberduck, WordPress

**SKILLS AND AWARDS**

-   Proficient in AP Style, data analysis and visualization (R, Google Sheets, Flourish), Adobe Audition, Adobe
    Lightroom, photography, field recording (audio)

-   5th place in the ACP Multimedia Story of the Year (Podcast) contest (2024) for “A look into The Daily’s coverage of the Deering Meadow encampment”
